version: '3.8'

services:
  backend:
    image: 689916825005.dkr.ecr.us-west-2.amazonaws.com/buildforce-be:latest

    container_name: buildforce-be

    restart: always

    ports:
      - "5000:5000"

    env_file:
      - .env

    environment:
      NODE_ENV: production
